---
abstract: 'a sub-class of Throwable::Error for system error objects'
author:
  - 'jason hord <pravus@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Throwable-SysError
no_index:
  directory:
    - inc
    - t
requires:
  Errno: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  Scalar::Util: 0
  Throwable::Error: 0
  namespace::autoclean: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.00
